### ISSUE TITLE
Scope level from 2 -> 12 causes weird sprint behavior

### ISSUE THREAD

**Issue by CJCrafter** [DeeCaaD/WeaponMechanics-wiki#3]
## Expected Behavior 
The stacky scope feature should be set to 12, and allow players to move around normally while their screen appears zoomed in.

## Observed Behavior
When going from scope level 2 to scope level 12, the player gets "stuck" in their block, and the screen zooms in. When trying to use WASD, the player doesn't move. If the player tried to sprint, their zoom effect gets reset (the player's screen no longer appears to be zoomed in), and the player can move normally

## Steps to Reproduce
Add this to a weapon
```yaml
  Scope:
    Trigger:
       Main_Hand: "LEFT_CLICK"
       Off_Hand: "RIGHT_CLICK"
    Zoom_Amount: 2
    Mechanics:
      Sounds:
        - custom:scope.in-0.5-1.0-0-0.05
    Zoom_Off:
      Mechanics:
        Sounds:
          - custom:scope.out-0.5-1.0-0-0.05
    Zoom_Stacking:
      Maximum_Stacks: 2
      Increase_Zoom_Per_Stack: 10
```
